[WFLY-18515] remove ssl quickstart
jbosstm/quickstart pull request #455
Opened 2024-03-12 15:06 UTC by marcosgopen

https://issues.redhat.com/browse/WFLY-18515

Since the wsat-simple was removed from wildfly/quickstart the ssl quickstart doesn't work anymore, so removing it.

2024-03-12 17:17 UTC, tomjenkinson commented
Thank you for finding this @marcosgopen

(Please can you say if WFLY-18515 caused our build to fail? If not this is an opportunity to review that part and make sure it would fail.)

2024-03-12 17:17 UTC, tomjenkinson approved these changes

2024-03-12 17:30 UTC, marcosgopen commented
> Thank you for finding this @marcosgopen
> 
> (Please can you say if WFLY-18515 caused our build to fail? If not this is an opportunity to review that part and make sure it would fail.)

Yes, it does. E.g. this is the failing build: https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/view/Pull/job/btny-pulls-narayana-quickstart/323/console

2024-03-13 09:27 UTC, marcosgopen commented
@mmusgrov Do you think I need to create a Jira to create a new ssl quickstart?

2024-03-13 09:37 UTC, mmusgrov requested changes
I'm all for removing WS quickstarts but we need a JBTM for it where we can justify it and track it. This qs resides in our repo and we are independent of WildFly. If the base WS functionality is still in narayana but WFLY no longer supports what we need then we either need justify why we are removing it from our repo or we need to investigate other platforms where we could run the quickstart.

2024-03-13 10:00 UTC, marcosgopen commented
> I'm all for removing WS quickstarts but we need a JBTM for it where we can justify it and track it. This qs resides in our repo and we are independent of WildFly. If the base WS functionality is still in narayana but WFLY no longer supports what we need then we either need justify why we are removing it from our repo or we need to investigate other platforms where we could run the quickstart.
> 
> @marcosgopen Can we find out why it was removed as out of date and whether or not there was a discussion about bringing it up to date?

Thanks Mike, I created the JBTM and asked to Eduardo. I will let you know and update the JBTM soon

2024-03-13 10:13 UTC, mmusgrov commented
But if we can't remove it immediately then it does need disabling in the pom until we can make a decision.

2024-03-13 12:00 UTC, marcosgopen commented
> But if we can't remove it immediately then it does need disabling in the pom until we can make a decision.

Thanks Mike, I changed the description of this PR, I updated the PR so that it disable the quickstart and I created an extra JBTM to update/remove the quickstart (see this PR description)

2024-03-13 14:44 UTC, tomjenkinson approved these changes

2024-03-13 14:45 UTC, tomjenkinson requested changes
Actually I think if we are just disabling it, it's worth noting the reason in the https://github.com/jbosstm/quickstart/blob/main/XTS/ssl/README.md so that people don't try to run it manually.

2024-03-13 14:50 UTC, marcosgopen commented
> Actually I think if we are just disabling it, it's worth noting the reason in the https://github.com/jbosstm/quickstart/blob/main/XTS/ssl/README.md so that people don't try to run it manually.

Good point! Thanks @tomjenkinson !

2024-03-13 15:19 UTC, tomjenkinson approved these changes
Thank you!

2024-03-13 21:02 UTC, mmusgrov approved these changes
Looks good now, thanks.

2024-03-14 09:33 UTC, merged